### ISSUE TITLE
Add More Adjectives

### ISSUE THREAD

**Issue by chrisburgin95** [chrisburgin95/bands_of_yore#7]
In `/app/data/adjectives.js` add more adjectives that might be used in the olden times. The adjectives are a held in an array. It will be very easy and simple to add them! 

Requirements
- Have fun!
- Be Creative!

**Comment by raindogg** [comment]
Hi, 

I really like this project! I added a couple adjectives in this [PR](https://github.com/chrisburgin95/bands_of_yore/pull/27). Hope you like them!

**Comment by chrisburgin95** [comment]
Gonna close this out! Thanks so much to everyone who added adjectives! We have so many now! Still need lots of verbs and nouns! So check out the other issues!!

Happy hacktoberfest everyone!
